version: '2'
services:
#  wms-mysql:
#    build:
#      context: ./db
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    restart: always
#    container_name: wms-mysql
#    image: wms-mysql
#    ports:
#      - 3306:3306
#
#  wms-redis:
#    image: redis:6.0
#    ports:
#      - 6379:6379
#    restart: always
#    container_name: wms-redis
#    hostname: wms-redis
#
  wms-register:
    build:
      context: ./wms-register
    restart: always
    ports:
      - 8848:8848
    container_name: wms-register
    hostname: wms-register
    image: wms-register
#
#  wms-gateway:
#    build:
#      context: ./wms-gateway
#    restart: always
#    ports:
#      - 9999:9999
#    container_name: wms-gateway
#    hostname: wms-gateway
#    image: wms-gateway
#  wms-auth:
#    build:
#      context: ./wms-auth
#    restart: always
#    container_name: wms-auth
#    hostname: wms-auth
#    image: wms-auth
#
#  wms-upms:
#    build:
#      context: ./wms-upms/wms-upms-biz
#    restart: always
#    container_name: wms-upms
#    hostname: wms-upms
#    image: wms-upms
#
#  wms-monitor:
#    build:
#      context: ./wms-visual/wms-monitor
#    restart: always
#    ports:
#      - 5001:5001
#    container_name: wms-monitor
#    hostname: wms-monitor
#    image: wms-monitor
#
#  wms-sentinel:
#    build:
#      context: ./wms-visual/wms-sentinel-dashboard
#    restart: always
#    image: wms-sentinel
#    container_name: wms-sentinel
#    ports:
#      - 5003:5003
#
#  wms-codegen:
#    build:
#      context: ./wms-visual/wms-codegen
#    restart: always
#    container_name: wms-codegen
#    hostname: wms-codegen
#    image: wms-codegen
#
#  wms-job:
#    build:
#      context: ./wms-visual/wms-xxl-job-admin
#    restart: always
#    container_name: wms-job
#    hostname: wms-job
#    image: wms-job
#    ports:
#      - 5004:5004